replicaCount: 2
image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent
containerPort: 5000
service:
  type: LoadBalancer
  port: 80
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }
serviceAccount:
  create: true
  name: webapp
  annotations: {}
env: []
envFrom: []
aws:
  region: us-east-1
secrets:
  dbArn: ""
