serviceAccount:
  create: true
  name: orders-consumer
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::124482837913:role/irsa-webapp-dev-orders-consumer"

image:
  repository: public.ecr.aws/docker/library/busybox
  tag: latest

env:
  - name: AWS_REGION
    value: "us-east-1"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "boot-dulb3pqv.c3.kafka-serverless.us-east-1.amazonaws.com:9098"
  - name: KAFKA_SECURITY_PROTOCOL
    value: "SASL_SSL"
  - name: KAFKA_SASL_MECHANISM
    value: "AWS_MSK_IAM"
